= dotfiles

My dotfiles on Arch Linux.

== Desktop environment

|===
| Window Manager | bspwm
| Editor         | vim
| Input Method   | uim
| Terminal       | st
| GTK Theme      | Arc-Darker
|===

== Usage

You need clone the repository to under your "${HOME}".

[source, sh]
----
cd ~
git clone https://github.com/odknt/dotfiles.git
----

Install dependencies by using `pacman` and AUR helper.

[source, sh]
----
# Base Packages (CLI)
cat .base.plist | sudo pacman -S --needed --noconfirm -
# GUI packages
cat .gui.plist | sudo pacman -S --needed --noconfirm -
# AUR packages
cat .aur.plist | YOUR_AUR_HELPER -S --needed --noconfirm -
----

=== Enable configs

Use `stow` for enable configuration of the dotfiles.

[source, sh]
----
cd ~/dotfiles

# stow <directory>
stow vim

# or stow -d ~/dotfiles -t ~ vim
----

== Optional

=== vim

Plugins install required [volt](https://github.com/vim-volt/volt).

If you need install all plugins then execute the following command after creates symlink from `vim` to the home directory by using `stow`.
Also need set `VOLTPATH` to "${HOME}/.vim/volt". If you were executed `stow profile` then `VOLTPATH` has been set in `.profile`.

[source, sh]
----
volt get -l
----

=== Pulseaudio with ALSA

You'd like to avoid sound trouble, use PulseAudio.

[source, sh]
----
systemctl --user start pulseaudio
systemctl --user enable pulseaudio
----

== Start X

[source, sh]
----
startx ~/.xinitrc <WM | application>

# or

xinit <WM | application>
----

== Performance settings

=== makepkg

If you'd like to improved performance on `makepkg` then edit below options in `/etc/makepkg.conf`.

[source, conf]
----
MAKEFLAGS="-j8" # set number of CPU cores at least

COMPRESSGZ=(pigz -c -f -n)
COMPRESSBZ2=(pbzip2 -c -f)
COMPRESSXZ=(xz -T O -c -z -)
COMPRESSZST=(zstdmt -c -z -q -)
----
