[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'nixprime/cpsm'
build = './install.sh'

[[plugins]]
repo = 'vim-scripts/grep.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make -f make_unix.mak'

[[plugins]]
repo = 'xolox/vim-misc'

[[plugins]]
repo = 'xolox/vim-session'
depends = [ 'vim-misc' ]

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'SirVer/ultisnips'
depends = [ 'vim-snippets' ]

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'moll/vim-bbye'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-scripts/PreserveNoEOL'

[[plugins]]
repo = 'jsfaint/gen_tags.vim'

[[plugins]]
repo = 'syngan/vim-vimlint'

[[plugins]]
repo = 'cohama/vim-hier'

[[plugins]]
repo = 'janko-m/vim-test'

[[plugins]]
repo = 'Valloric/YouCompleteMe'
build = './install.py --gocode-completer --tern-completer --racer-completer --system-boost'

[[plugins]]
repo = 'glidenote/memolist.vim'

[[plugins]]
repo = 'dannyob/quickfixstatus'
