if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8
set fileencoding=utf-8 fileencodings=utf-8,sjis,enc-jp bomb binary nofixendofline
filetype off
filetype plugin indent off
set smartindent autoindent
set ruler nonumber regexpengine=1
set nocompatible nostartofline nowritebackup notitle
set noequalalways splitbelow splitright
set lazyredraw ttyfast novisualbell t_ut= belloff=all
set background=dark display=lastline textwidth=0
set mouse=
set completeopt=menuone complete=. pumheight=20
set nohlsearch incsearch ignorecase smartcase wrapscan noshowmatch
set dictionary=/usr/share/dict/words
set thesaurus=/usr/share/mythes/th_en_US_v2.dat
set emoji ambiwidth=double
set switchbuf=usetab,newtab
set formatoptions=q
set cmdheight=1 laststatus=0
set showmode modeline modelines=10

hi SpecialKey ctermbg=none ctermfg=12
if &encoding ==? 'utf-8'
  exec "set fillchars=vert:\u23AE,fold:\u23BC,diff:\u23BC"
  set list listchars=tab:˫\ ,trail:-,extends:»,precedes:«,nbsp:%
else
  exec 'set list fillchars=vert:\|,fold:-,diff:.'
endif
hi VertSplit ctermfg=black ctermbg=61

if executable('rg')
  set grepformat=%f:%l:%c:%m,%f:%l:%m
  set grepprg=rg\ --vimgrep\ --no-heading\ --glob\ '!tags'
endif
command! -nargs=+ Grep execute 'silent grep! <args>' | copen 20

function! s:mkdir_if_not_exists(dir)
  if !isdirectory(expand(a:dir))
    call mkdir(expand(a:dir), 'p')
  endif
endfunction
call s:mkdir_if_not_exists('~/.cache/vim/swap')
set directory=~/.cache/vim/swap

set linebreak showbreak=> breakat=\ \ ;:,!?
if exists('+breakindent')
  set wrap breakindent breakindentopt=shift:4,sbr
else
  set nowrap
endif

if has('unnamedplus')
  set clipboard^=unnamed,unnamedplus
  augroup vimrc_clipboard
    au!
    au VimLeave * call system("xclip -sel c", getreg("+"))
  augroup end
elseif has('clipboard')
  set clipboard^=unnamed
endif

"" for tmux
if $TERM =~? 'screen*'
  set termguicolors
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

let @d = ':bp|bw! #'

nnoremap <C-p> :FZFFiles<CR>
command! FZFFiles call fzf#run(fzf#wrap({
  \ 'source': 'find * -type f | grep -Pv "((.git|.hg|.svn|node_modules|bower_components|vendors|vendor|target).+|.+\.(exe|so|dll|class|a|o|pyc|ejs))"',
  \ }))

if filereadable(expand('~/.vim/vimrc-local'))
  source ~/.vim/vimrc-local
endif

filetype on
