#! /bin/sh
# vim: sw=2 ts=2 sts=2 et

sxhkd &

bspc query -M | while read -r id; do
  bspc monitor "${id}" -d 壱 弐 参 肆 伍
done

#
# Configs
#

bspc config border_width 3
bspc config window_gap 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config click_to_focus button1
bspc config honor_size_hints floating
bspc config ignore_ewmh_focus true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4
bspc config external_rules_command "${HOME}/.config/bspwm/external_rules"

#
# Colors
#

bspc config focused_border_color '#A73E28'
bspc config normal_border_color '#292825'

#
# Rules
#

bspc rule -a Lxappearance state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Uim-pref-gtk state=floating
bspc rule -a Nsxiv state=floating
bspc rule -a '*:Browser' state=floating
bspc rule -a '*:Toolkit' state=floating
bspc rule -a '*:Places' state=floating
bspc rule -a rdesktop border=off
bspc rule -a mpv state=floating
bspc rule -a ssp.exe manage=off

# background (by using "feh" package)
if type feh > /dev/null && [ -f "${HOME}/.fehbg" ]; then
  "${HOME}/.fehbg"
fi

# autostart (by using "dex" package)
dex -a

# status bar
bspwmbar &
