#!/usr/bin/env python
# arguments: 1=Window ID, 2=Class, 3=Instance

import dataclasses
import re
import subprocess
import sys
from enum import Enum

from typing import Any, List, Optional, Self, Type, TypeVar

T = TypeVar('T', bound='XProperty')

rName = r'(?<=WM_NAME\(STRING\) = ").*(?=")'
rWmWindowRole = r'(?<=WM_WINDOW_ROLE\(STRING\) = ").*(?=")'
rNetWmWindowType = r'(?<=_NET_WM_WINDOW_TYPE\(ATOM\) = ).*(?=)'
rLocation = r'(?<=specified location: ).*(?=)'
rGravity = r'(?<=window gravity: ).*(?=)'


class Toggle(Enum):
    ON = 'on'
    OFF = 'off'

    def __str__(self) -> str: return self.value


class State(Enum):
    TILED = 'tiled'
    PSEUDO_TILED = 'pseudo'
    FLOATING = 'floating'
    FULLSCREEN = 'fullscreen'

    def __str__(self) -> str: return self.value


@dataclasses.dataclass
class Rule:
    monitor: str = ''
    desktop: str = ''
    node: str = ''
    state: State = State.TILED
    layer: str = ''
    honor_size_hints: str = ''
    split_dir: str = ''
    split_ratio: str = ''
    hidden: Toggle = Toggle.OFF
    sticky: Toggle = Toggle.OFF
    private: Toggle = Toggle.OFF
    locked: Toggle = Toggle.OFF
    marked: Toggle = Toggle.OFF
    center: Toggle = Toggle.OFF
    follow: Toggle = Toggle.OFF
    manage: Toggle = Toggle.OFF
    focus: Toggle = Toggle.OFF
    border: Toggle = Toggle.OFF
    rectangle: str = ''

    def __str__(self):
        rule: List[str] = []
        for key, val in self.__dict__.items():
            rule.append(f'{key}={val}')
        return ' '.join(rule)

    def __getitem__(self, key):
        return self.__dict__[key]

    @classmethod
    def parse(cls, data: str) -> Self:
        values: dict[str, Any] = {}
        fields = [v.name for v in dataclasses.fields(Rule)]
        for setting in data.split(' '):
            v = setting.split('=')
            if v[0] in fields:
                values[v[0]] = v[1]
        return Rule(**values)


class XProperty:
    def __init__(self, xprop: str):
        self.name = self.search(rName, xprop)
        self.gravity = self.search(rGravity, xprop)
        self.location = self.search(rLocation, xprop)
        self.window_type = self.search(rNetWmWindowType, xprop)
        self.window_role = self.search(rWmWindowRole, xprop)

    @classmethod
    def xprop(cls: Type[T], wid: str) -> T:
        output = subprocess.check_output(['xprop', '-id', wid]).decode('utf-8')
        return cls(output)

    def search(self, regexp: str, text: str) -> str|None:
        match = re.search(regexp, text)
        if match is None:
            return None
        return match.group(0)

    def is_dialog(self) -> bool:
        if self.window_type is None:
            return False
        return self.window_type == '_NET_WM_WINDOW_TYPE_DIALOG'

    def is_floating(self) -> bool:
        if self.gravity is not None and self.location:
            return True
        return False

    def apply(self, rule: Rule) -> Rule:
        if self.is_floating():
            rule.state = State.FLOATING
        elif self.is_dialog():
            rule.state = State.FLOATING
            rule.border = Toggle.ON

        if self.window_role == 'Popup':
            rule.border = Toggle.OFF
            rule.manage = Toggle.OFF
        elif self.window_role == 'toolbox':
            rule.state = State.FLOATING

        return rule


if __name__ == '__main__':
    try:
        rule = Rule.parse(sys.argv[4])
        newRule = XProperty.xprop(sys.argv[1]).apply(Rule(**rule.__dict__))

        rules: list[str] = []
        for k in [v.name for v in dataclasses.fields(Rule)]:
            if rule[k] != newRule[k]:
                rules.append(f'{k}={newRule[k]}')
        print(' '.join(rules))
    except Exception as e:
        with open("/tmp/external_rules.log", "a+") as f:
            f.write(f'{e}\n')
