#!/bin/sh

focused_node_state() {
  monitor="$(bspc query -M -m --names)"
  bspc subscribe report -c 1 \
  | grep -Po "${monitor}.*?:G[SPL]?:?" \
  | grep -Po "(?<=:T)[TPF=@](?=:)"
}

switch_to_floating() {
  bspc node last.floating.local -f \
  || bspc node any.floating.local -f
}

switch_to_tiled() {
  bspc node last.tiled.local -f \
  || bspc node any.tiled.local -f
}

case "$(focused_node_state)" in
  T) switch_to_floating ;;
  F) switch_to_tiled    ;;
esac

echo $(focused_node_state)
