if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8
set binary nofixendofline
filetype off
filetype plugin indent off
set autoindent expandtab copyindent preserveindent
set nowritebackup notitle noswapfile
set lazyredraw ttyfast novisualbell belloff=all background=dark
set mouse=
set emoji ambiwidth=double
set switchbuf=usetab,newtab
set showmode modeline modelines=10
set hlsearch ignorecase smartcase incsearch wildmenu
set list listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%
set clipboard^=unnamedplus
set viminfo+=n~/.cache/vim/viminfo
set grepprg=rg\ --vimgrep\ --no-heading
set grepformat=%f:%l:%c:%m,%f:%l:%m

hi SpecialKey ctermbg=none ctermfg=12
hi NonText ctermbg=none ctermfg=1
hi VertSplit ctermfg=black ctermbg=61
hi MatchParen ctermfg=0
hi DiffAdd ctermfg=0 ctermbg=2
hi DiffChange ctermfg=0 ctermbg=3
hi DiffDelete ctermfg=15 ctermbg=1

let @d = ':bp|bw! #'
let g:netrw_use_errorwindow = 0
let g:netrw_banner = 0
let g:fzf_action = {'ctrl-t': 'tab drop', 'ctrl-x': 'split', 'ctrl-v': 'vsplit'}
nnoremap <C-p> :FZF<CR>

augroup VIMRC
  autocmd VimLeave * call system("xclip -sel c", getreg('+'))
augroup END

filetype plugin on
