if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8
set fileencoding=utf-8 fileencodings=utf-8,sjis,enc-jp bomb binary nofixendofline
filetype off
filetype plugin indent off
set autoindent expandtab
set nowritebackup notitle noswapfile
set lazyredraw ttyfast novisualbell belloff=all background=dark
set mouse=
set emoji ambiwidth=double
set switchbuf=usetab,newtab
set showmode modeline modelines=10
set hlsearch ignorecase smartcase incsearch wildmenu
set list listchars=tab:»-,trail:-,extends:»,precedes:«,nbsp:%
set clipboard^=unnamedplus

hi SpecialKey ctermbg=none ctermfg=12
hi NonText ctermbg=none ctermfg=1
hi VertSplit ctermfg=black ctermbg=61
hi MatchParen ctermfg=0
hi DiffAdd ctermfg=0 ctermbg=2
hi DiffChange ctermfg=0 ctermbg=3
hi DiffDelete ctermfg=15 ctermbg=1

let @d = ':bp|bw! #'
let g:netrw_use_errorwindow = 0
let g:netrw_banner = 0
let g:fzf_action = {'ctrl-t': 'tab drop', 'ctrl-x': 'split', 'ctrl-v': 'vsplit'}

command! FZFFiles call fzf#run(fzf#wrap({'source':'rg --no-ignore-vcs --files --hidden --follow --ignore-file ~/.rgignore'}))
nnoremap <C-p> :FZF<CR>

filetype on
