#! /bin/sh
#
# Example panel for lemonbar

load_profile() {
    . "${0%/*}/profile"
}
trap load_profile USR1

load_profile

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
    case $line in
        C*)
            # date output
            cal="  ${line#?}  "
            ;;
        S*)
            # clock output
            sys="%{B$COLOR_SYS_BG}  ${line#?}  %{B-}"
            ;;
        T*)
            # xtitle output
            title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
            title="%{S0}${title}%{S1}${title}"
            ;;
        W*)
            # bspwm's state
            wm=""
            snum=0
            dnum=1
            IFS=':'
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                name=${item#?}
                case $item in
                    [mM]*)
                        [ $num_mon -lt 2 ] && shift && continue
                        [ $dnum -gt 1 ] && snum="$((snum + 1))"
                        case $item in
                            m*)
                                # monitor
                                FG=$COLOR_MONITOR_FG
                                BG=$COLOR_MONITOR_BG
                                ;;
                            M*)
                                # focused monitor
                                FG=$COLOR_FOCUSED_MONITOR_FG
                                BG=$COLOR_FOCUSED_MONITOR_BG
                                ;;
                        esac
                        wm="${wm}%{S${snum}}%{F${FG}}%{B${BG}}%{A:bspc monitor -m $((snum + 1)) -f ${name}:}   ${name}  %{A}%{B-}%{F-}"
                        dnum=1
                        ;;
                    [fFoOuU]*)
                        case $item in
                            f*)
                                # free desktop
                                FG=$COLOR_FREE_FG
                                BG=$COLOR_FREE_BG
                                NAME=" ${name} "
                                ;;
                            F*)
                                # focused free desktop
                                FG=$COLOR_FOCUSED_FREE_FG
                                BG=$COLOR_FOCUSED_FREE_BG
                                NAME=" ${name} "
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_OCCUPIED_FG
                                BG=$COLOR_OCCUPIED_BG
                                NAME="%{B${BG}}%{U${FG}}%{+u} ${name} %{-u}%{U-}%{B-}"
                                ;;
                            O*)
                                # focused occupied desktop
                                FG=$COLOR_FOCUSED_OCCUPIED_FG
                                BG=$COLOR_FOCUSED_OCCUPIED_BG
                                NAME="%{B${BG}}%{U${FG}}%{+u} ${name} %{-u}%{U-}%{B-}"
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_URGENT_FG
                                BG=$COLOR_URGENT_BG
                                NAME="%{B${BG}}%{U${FG}}%{+u} ${name} %{-u}%{U-}%{B-}"
                                ;;
                            U*)
                                # focused urgent desktop
                                FG=$COLOR_FOCUSED_URGENT_FG
                                BG=$COLOR_FOCUSED_URGENT_BG
                                NAME="%{B${BG}}%{U${FG}}%{+u} ${name} %{-u}%{U-}%{B-}"
                                ;;
                        esac
                        wm="${wm}%{O3}%{A:bspc desktop -f "$(bspc query -D -m "^$((snum + 1))" | awk "NR==${dnum}")":}${NAME}%{A}%{O3}"
                        dnum="$((dnum + 1))"
                        ;;
                    [LTG]*)
                        # layout, state and flags
                        # wm="${wm}%{F$COLOR_STATE_FG}%{B$COLOR_STATE_BG} ${name} %{B-}%{F-}"
                        ;;
                esac
                shift
            done
            ;;
    esac
    sys="%{S0}${cal}${sys}%{S1}${cal}${sys}"
    printf "%s\n" "%{l}${wm}%{c}${title}%{r}${cal}${sys}"
done
