#! /bin/sh

. "${0%/*}/profile"

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "${PANEL_FIFO}" ] && rm "${PANEL_FIFO}"
mkfifo "${PANEL_FIFO}"

bspc config top_padding "$(( PANEL_HEIGHT + 2 ))"

bspc subscribe report > "${PANEL_FIFO}" &
xtitle -sf "T%s\n" > "${PANEL_FIFO}" &
# hwclock -sf 'S%a %H:%M' > "${PANEL_FIFO}" &

while true; do
    echo "S$(date +'%Y-%m-%d (%a) %H:%M:%S')"
    sleep 1
done > "${PANEL_FIFO}" &

. "${0%/*}/panel_colors"

"${0%/*}/panel_bar" < "${PANEL_FIFO}" | lemonbar -a 32 -n "${PANEL_WM_NAME}" -g x${PANEL_HEIGHT} -f "${FONT_GLOBAL}" -F "${FG_GLOBAL}" -B "${BG_GLOBAL}" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    sleep 0.05
    wid=$(xdo id -a "$PANEL_WM_NAME")
    tries_left=$((tries_left - 1))
done
[ -n "${wid}" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "${wid}"

wait
