#!/bin/sh
# vim: sw=2 ts=2 sts=2 et

readonly MONITORS="$(bspc query -M)"
readonly DESKTOPS="$(bspc query -D -m)"

move_to_desktop() {
  [ -z "${1}" ] && return
  id="$(echo "${DESKTOPS}" | sed -n "${1}p")"

  [ -z "${id}" ] && return
  bspc node -d "${id}"
}

move_to_monitor() {
  [ -z "${1}" ] && return
  bspc node -m "^${1}"
}

case "${1:-}" in
  D) move_to_desktop "${2:-}" ;;
  M) move_to_monitor "${2:-}" ;;
esac
