#! /bin/sh
# vim: sw=2 ts=2 sts=2 et

sxhkd &

bspc query -M | while read -r id; do
  bspc monitor "${id}" -d 壱 弐 参 肆 伍
done

#
# Configs
#

bspc config border_width            3
bspc config window_gap              10

bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config click_to_focus          true
bspc config history_aware_focus     false
bspc config ignore_ewmh_focus       true
bspc config auto_cancel             true
bspc config auto_alternate          true
bspc config pointer_follows_monitor true
bspc config pointer_modifier        mod4
bspc config external_rules_command  ~/.config/bspwm/external_rules

#
# Colors
#

bspc config focused_border_color '#A73E28'
bspc config normal_border_color  '#292825'

#
# Rules
#

bspc rule -a Sylpheed:compose state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Pcmanfm state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Uim-pref-gtk state=floating
bspc rule -a Sxiv state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a 'Firefox:*' state=floating
bspc rule -a Firefox:Navigator state=tiled
bspc rule -a 'Firefox-nightly:*' state=floating
bspc rule -a Firefox-nightly:Navigator state=tiled
bspc rule -a xfreerdp border=off
bspc rule -a Ninix_main.rb manage=off
bspc rule -a steam.exe border=off
bspc rule -a mpv state=floating
bspc rule -a URxvt:tty-clock border=off state=floating rectangle=220x130+0+0
bspc rule -a Pinentry state=floating

# scratchpad
bspc rule -a URxvt:scratchpad sticky=on state=floating hidden=on

# background image
nitrogen --restore

# compositor
compton &

# panel
for mon in $(bspc query -M --names); do
  MONITOR="${mon}" polybar -q bspwm &
done
